site_name: CGSim — Simulation Framework For Large-Scale Distributed Computing
site_description: CGSim — Simulation Framework For Large-Scale Distributed Computing
site_author: REDWOOD Collaboration
repo_name: CGSim
repo_url: https://github.com/REDWOOD24/CGSim


theme:
    name: material

nav:
    - Home: 'index.md'
    - 'Install Libraries & Tools': 'install.md'
    - 'Getting Started with CGSim':
      - Configuration: 'configuration.md'
      - Computing Grid: 'computing_grid.md'
   
    - 'Plugin Architecture':
      - 'Plugin Examples': 'plugin_examples.md'
      - 'Plugin Support': 'plugin_support.md'

    - Simulation tools:
      - 'File System Manager': 'file_manager.md'
      - 'Site Manager': 'site_manager.md'
      - 'Policy Manager': 'policy_manager.md'
      
    - Visualization:
      - 'CGSim Application': 'visualization.md'
      
    - For Developers:
        - 'Troubleshooting': 'troubleshooting.md'
        - 'Contributing to the Documentation': 'docs-contrib.md'
        - 'Dev FAQ': 'dev/dev-faq.md'

    - FAQ: 'faq.md'
    - Papers & Presentations: 'papers.md'
    - Team & History: 'team.md'
    - Contact: 'contact.md'

extra_css:
    - material_nested_lists_rendering.css

markdown_extensions:
    - smarty                # to use 'SmartyPants' typography extensions as '---' for em-dashes
    - admonition            # to use notes, warnings, tips, ...
    - footnotes             # to set footnotes
    - pymdownx.superfences  
    - pymdownx.superfences: # to use code blocks nested under lists items
        # make exceptions to highlighting of code:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid
    - toc:
        permalink: true
    - markdown_include.include:
        base_path: docs
    - pymdownx.arithmatex:  # to use LaTeX syntax in Markdown files
        generic: true
    #- markdown.extensions.attr_list # to use custom css settings, e.g. {: .center}. Not used now

plugins:
  - search
  - macros:
        module_name: imgutils
        verbose: true # enables debug through the 'chatter' method
  - mermaid2 # for diagrams
  #- git-revision-date #TODO: the mkdocs docker image apparently lacks the git exec, so this cannot be used. Update the image!

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
